### ISSUE TITLE
remove shared gemset - optimize dockerfile example 

### ISSUE THREAD

**Issue by rosskevin** [alienfast/docker-rails#25]
There is no need to force use of a specific gemset volume, the user has greater control of this and other caching control via their own `Dockerfile`.
- [x] remove gemset code
- [x] document a normal config
- [x] document an engine config
- [x] update test examples  and remove `bundle install` there

**Comment by britton** [comment]
What would it look like to define a gemset volume via a Dockerfile?

**Comment by rosskevin** [comment]
@britton - [convox/rails](https://github.com/convox/rails#usage) has a good example.  I've found that this is a more flexible approach and less complex.  This way (without the extra data container) simply uses docker's inherent file layering to rebuild the image when necessary.

Mine is a bit more complex because I also run `npm install`.  Here is a [real-life gist of a rails engine + dummy app + node + npm + flowtype (dependency)](https://gist.github.com/rosskevin/e2b9f6ebe6e5b1e3a383ef0d9869dcea).  This is probably too much information, but I think you can pare it down.  

As an aside, if you want to PR a change to the docs, it's always welcome.

**Comment by britton** [comment]
That's what I needed.  Thanks @rosskevin!
